### ISSUE TITLE
standard-module-name-resolver: cycle in loading

### ISSUE THREAD

**Issue by jsmaniac** [racket/errortrace#13]
Using Racket 6.8.0.1, After doing `raco pkg install phc-adt`, if I try to run the following file in DrRacket with debugging enabled:

```racket
#lang racket
(require phc-adt)
```

I get this error:

```
standard-module-name-resolver: cycle in loading
  at path: /home/georges/.racket/snapshot/pkgs/errortrace-lib/errortrace/errortrace-lib.rkt
  paths:
   /home/georges/.racket/snapshot/pkgs/errortrace-lib/errortrace/errortrace-lib.rkt
```

**Comment by jsmaniac** [comment]
This might be related to #14.

I was able to reproduce this bug with a much simpler setup.

`a.rkt`:
```
#lang scribble/lp2
@chunk[<*>
       (module m typed/racket)]
```

`b.rkt`
```racket
#lang racket
(require "a.rkt")
```

**Comment by jsmaniac** [comment]
Note that this bug occurs only if debugging is enabled AND the option "populate compiled directories" is checked in DrRacket.

**Comment by florence** [comment]
I'm not seeing this on 6.8.0.2 (with either phc-adt or the smaller scribble/lp example).

If you blow away your `compiled` directories and rebuild does this still happen?

**Comment by jsmaniac** [comment]
@florence Ok I'll try after updating (I run a minimal racket + all packages in ~/.racket, so updates take a while, I'll leave this to run a bit later).

By the way, what's the recommended way to upgrade / clean the `compiled` directories? I usually have to delete all the `compiled` directories with `find -name compiled -type d -print0 | xargs -0 rm -rf`, and get rid of the `doc` directories too, both in `~/.racket` and in places where I have linked packages, but it is kind of a pain to do.

**Comment by florence** [comment]
iirc `raco setup -c` will force everything to rebuild: but I was just thinking of removing the compiled directories for phc and maybe errortrace (and the a.rkt and b.rkt).

**Comment by jsmaniac** [comment]
I cleaned the `compiled` directories for `errortrace`, `a.rkt` and `b.rkt`, and the error doesn't occur anymore, neither for `a.rkt` nor for `phc-adt`, so I'm closing this. Thanks for looking at it.

I had seen `raco setup -c`, but I wasn't sure if it was the right tool (and iirc it has a tendency to try to delete the read-only `compiled` directories in `/usr` and fails, I'll see if it does that this time, and report it if needed).

**Comment by rfindler** [comment]
There is an error in the way that DrRacket set ups the environment when it manages compiled files. It can be tricky to trigger it, but probably that was responsible for getting your .zo files into a bad state.

(This is a known bug, tho, so I think it is good that this issue remain closed.)
