### ISSUE TITLE
#%require: unbound identifier

### ISSUE THREAD

**Issue by jsmaniac** [racket/errortrace#14]
Using Racket 6.8.0.1, After doing raco pkg install phc-adt, if I try to run the following file in DrRacket with debugging enabled:

```racket
#lang racket
(require (for-template phc-adt))
```

I get this error:

```
.racket/snapshot/pkgs/errortrace-lib/errortrace/private/utils.rkt:26:18: #%require: unbound identifier;
 also, no #%app syntax transformer is bound in: #%require
```

Might be related to #13.

**Comment by jsmaniac** [comment]
Note that this bug occurs only if debugging is enabled AND the option "populate compiled directories" is checked in DrRacket.

**Comment by florence** [comment]
This is not a regression (I see it on 6.7).

Still digging into the cause.

**Comment by florence** [comment]
I've narrowed the issue down to the following:

main.rkt:
```
#lang racket
(require errortrace/errortrace-lib)
(current-compile (make-errortrace-compile-handler))
(dynamic-require "template.rkt" #f)
```

template.rkt:
```
#lang racket
(require (for-template "eval.rkt"))
```

eval.rkt:
```
#lang racket
(begin-for-syntax
  (parameterize ([current-namespace (module->namespace 'racket/base)])
    (eval 1)))
```

and run `racket main.rkt`. 

The last thing that goes through the errortrace compile handler is #<syntax 1>, from eval.rkt.  `racket template.rkt` doesn't error. 

@mflatt I don't really understand what a phase 1 eval means when required for template, so I'm going to kick this over to you.
